config/routes.rb
Rails.application.routes.draw do
 root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: [:destroy]

    #  get 'lists', to: 'lists#index'
    #   get 'lists/new', to: 'lists#new'
    #  get 'lists/:id', to: 'lists#show'
    #  post 'lists', to: 'lists#create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

# get 'lists', to: 'lists#index'       # Affiche toutes les listes
# get 'lists/new', to: 'lists#new'    # Formulaire pour créer une nouvelle liste
# post 'lists', to: 'lists#create'    # Crée une nouvelle liste
# get 'lists/:id', to: 'lists#show'   # Affiche une liste spécifique

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie_id, :scope => [:list_id]
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: :true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: :true
  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @list.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@list)
   else
  render :new, status: :unprocessable_entity
  end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id]) # Trouver le signet par son ID
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'deleted!'
  end


  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    @movies = Movie.all
  end

  def show
    @bookmark = Bookmark.new
    #@list = List.find(params[:id])
  end

   def new
     @list = List.new
   end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
   else
  render :new, status: :unprocessable_entity
  end
 end

 private


  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All Movies</h1>
<ul>
  <% @movies.each do |movie| %>
    <li>
      <h2><%= movie.title %></h2>
      <p><%= movie.overview %></p>
      <img src="<%= movie.poster_url %>" alt="<%= movie.title %>" style="width: 200px; height: auto;">
    </li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url, label: "URL de l'image" %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<div class="position-relative">
  
    <h1><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>
<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
    <div>
      <button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        add a movie
      </button>
      <%= link_to "delete this list", list_path(@list), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    </div>
  </div>
  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <hr class="my-5">
  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>Reviews</h3>
      <% if @list.reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this list</em></small>
      <% end %>
      <% @list.reviews.each do |review| %>
        <div>
          <% review.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
    </div>
    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3">
        <h5>Add your review</h5>
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>
          <%= f.input :rating, as: :select, collection: (1..5), required: true, label: false, input_html: { data: { controller: "star-rating" } } %>
          <%= f.submit class: "btn btn-flat mt-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "bookmarks/modal", list: @list, bookmark: @bookmark %>